const companyTypes = {
  FETCH_COMPANIES_LIST_REQUEST: "FETCH_COMPANIES_LIST_REQUEST",
  FETCH_COMPANIES_LIST_SUCCESS: "FETCH_COMPANIES_LIST_SUCCESS",
  FETCH_COMPANIES_LIST_FAILED: "FETCH_COMPANIES_LIST_FAILED",
};

export default companyTypes;
