const personsTypes = {
  ADD_NEW_PERSON_REQUEST: "ADD_NEW_PERSON_REQUEST",
  ADD_NEW_PERSON_SUCCESS: "ADD_NEW_PERSON_SUCCESS",
  ADD_NEW_PERSON_FAILED: "ADD_NEW_PERSON_FAILED",

  GET_PERSONS_LIST_REQUEST: "GET_PERSONS_LIST_REQUEST",
  GET_PERSONS_LIST_SUCCESS: "GET_PERSONS_LIST_SUCCESS",
  GET_PERSONS_LIST_FAILED: "GET_PERSONS_LIST_FAILED",

  GET_SINGLE_PERSON_REQUEST: "GET_SINGLE_PERSON_REQUEST",
  GET_SINGLE_PERSON_SUCCESS: "GET_SINGLE_PERSON_SUCCESS",
  GET_SINGLE_PERSON_FAILED: "GET_SINGLE_PERSON_FAILED",

  GET_PERSONS_REQUEST: "GET_PERSONS_REQUEST",
  GET_PERSONS_SUCCESS: "GET_PERSONS_SUCCESS",
  GET_PERSONS_FAILED: "GET_PERSONS_FAILED",

  DELETE_PERSON_REQUEST: "DELETE_PERSON_REQUEST",
  DELETE_PERSON_SUCCESS: "DELETE_PERSON_SUCCESS",
  DELETE_PERSON_FAILED: "DELETE_PERSON_FAILED",

  DELETE_SELECTED_PERSON_REQUEST: "DELETE _SELECTED_PERSON_REQUEST",
  DELETE_SELECTED_PERSON_SUCCESS: "DELETE_ SELECTED_PERSON_SUCCESS",
  DELETE_SELECTED_PERSON_FAILED: "DELETE_SELECTED_PERSON_FAILED",

  CHANCE_PERSON_ACTIVITY_REQUEST: "CHANCE_PERSON_ACTIVITY_REQUEST",
  CHANCE_PERSON_ACTIVITY_SUCCESS: "CHANCE_PERSON_ACTIVITY_SUCCESS",
  CHANCE_PERSON_ACTIVITY_ERROR: "CHANCE_PERSON_ACTIVITY_ERROR",

  MAKE_PERSON_ACTIVE_REQUEST: "MAKE_PERSON_ACTIVE_REQUEST",
  MAKE_PERSON_ACTIVE_SUCCESS: "MAKE_PERSON_ACTIVE_SUCCESS",
  MAKE_PERSON_ACTIVE_ERROR: "MAKE_PERSON_ACTIVE_ERROR",

  MAKE_PERSON_UNACTIVE_REQUEST: "MAKE_PERSON_UNACTIVE_REQUEST",
  MAKE_PERSON_UNACTIVE_SUCCESS: "MAKE_PERSON_ACUNTIVE_SUCCESS",
  MAKE_PERSON_UNACTIVE_ERROR: "MAKE_PERSON_ACTIVEUN_ERROR",

  GENERATE_RFID_CODE_REQUEST: "GENERATE_RFID_CODE_REQUEST",
  GENERATE_RFID_CODE_SUCCESS: "GENERATE_RFID_CODE_SUCCESS",
  GENERATE_RFID_CODE_ERROR: "GENERATE_RFID_CODE_ERROR",

  GENERATE_PIN_CODE_REQUEST: "GENERATE_PIN_CODE_REQUEST",
  GENERATE_PIN_CODE_SUCCESS: "GENERATE_PIN_CODE_SUCCESS",
  GENERATE_PIN_CODE_ERROR: "GENERATE_PIN_CODE_ERROR",

  GENERATE_BAR_CODE_REQUEST: "GENERATE_BAR_CODE_REQUEST",
  GENERATE_BAR_CODE_SUCCESS: "GENERATE_BAR_CODE_SUCCESS",
  GENERATE_BAR_CODE_ERROR: "GENERATE_BAR_CODE_ERROR",

  GENERATE_LAST_BAR_CODE_REQUEST: "GENERATE_LAST_BAR_CODE_REQUEST",
  GENERATE_LAST_BAR_CODE_SUCCESS: "GENERATE_LAST_BAR_CODE_SUCCESS",
  GENERATE_LAST_BAR_CODE_ERROR: "GENERATE_LAST_BAR_CODE_ERROR",
};

export default personsTypes;
